---
- hosts: serveurs
  become: yes
  vars_prompt:
    - name: github_username
      prompt: "Entrez votre nom d'utilisateur GitHub "
      private: no
    - name: github_token
      prompt: "Entrez votre token GitHub "
      private: yes
  tasks:
    - name: Copie .gitconfig
      ansible.builtin.template:
        src: ../templates/gitconfig.j2
        dest: /root/.gitconfig
        owner: root
        group: root
        mode: '0644'
    - name: Configuration git-credentials
      ansible.builtin.template:
        src: ../templates/git-credentials.j2
        dest: /root/.git-credentials
        owner: root
        group: root
        mode: '0600'
