---
- name: Clone and update private repository
  hosts: serveurs

  tasks:
    - name: Clone or update repository
      git:
        repo: https://github.com/FERKOUSmaissara/tp-ansible-ferkous.git
        dest: /root/app
        version: main
        update: yes
