---
- name: Run Docker containers
  hosts: localhost
  connection: local
  become: yes

  vars:
    app_path: /root/app

  tasks:

    - name: Start containers with docker-compose
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: "{{ app_path }}"

    - name: Show running containers
      ansible.builtin.shell: docker ps
